/////////////////////////////////////////////////////////////////////////////
// Name:        camcreate.h
// Purpose:     
// Author:      K
// Modified by: 
// Created:     27/10/2013 15:43:45
// RCS-ID:      
// Copyright:   H
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/10/2013 15:43:45

#ifndef _CAMCREATE_H_
#define _CAMCREATE_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/spinctrl.h"
#include "wx/canvas/cameleon.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_A2DCAMCREATE 10013
#define ID__CamNameText 10000
#define ID_CamName 10014
#define ID_NrPortsText 10015
#define ID_NrPorts 10016
#define ID_InstSymbol 10017
#define ID__InstDiagram 10018
#define ID_InstGui 10019
#define ID_RADIOBUTTON 10020
#define ID_RADIOBUTTON1 10021
#define ID_RADIOBUTTON2 10022
#define ID_CamCreateOke 10023
#define ID_CamCreateCancel 10024
#define SYMBOL_A2DCAMCREATE_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_A2DCAMCREATE_TITLE _("camcreate")
#define SYMBOL_A2DCAMCREATE_IDNAME ID_A2DCAMCREATE
#define SYMBOL_A2DCAMCREATE_SIZE wxSize(400, 300)
#define SYMBOL_A2DCAMCREATE_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * a2dCamCreate class declaration
 */

class a2dCamCreate: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( a2dCamCreate )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    a2dCamCreate();
    a2dCamCreate( wxWindow* parent, a2dHabitat* habitat = NULL, wxWindowID id = SYMBOL_A2DCAMCREATE_IDNAME, const wxString& caption = SYMBOL_A2DCAMCREATE_TITLE, const wxPoint& pos = SYMBOL_A2DCAMCREATE_POSITION, const wxSize& size = SYMBOL_A2DCAMCREATE_SIZE, long style = SYMBOL_A2DCAMCREATE_STYLE );

    /// Creation
    bool Create( wxWindow* parent, a2dHabitat* habitat = NULL, wxWindowID id = SYMBOL_A2DCAMCREATE_IDNAME, const wxString& caption = SYMBOL_A2DCAMCREATE_TITLE, const wxPoint& pos = SYMBOL_A2DCAMCREATE_POSITION, const wxSize& size = SYMBOL_A2DCAMCREATE_SIZE, long style = SYMBOL_A2DCAMCREATE_STYLE );

    /// Destructor
    ~a2dCamCreate();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin a2dCamCreate event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CamCreateOke
    void OnCamCreateOkeClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CamCreateCancel
    void OnCancel( wxCommandEvent& event );

////@end a2dCamCreate event handler declarations

////@begin a2dCamCreate member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end a2dCamCreate member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin a2dCamCreate member variables
    a2dHabitat* m_habitat;
    wxTextCtrl* m_camName;
    wxSpinCtrl* m_NrPorts;
    wxCheckBox* m_symbol;
    wxCheckBox* m_diagram;
    wxCheckBox* m_gui;
    wxRadioButton* m_instanceSymbol;
    wxRadioButton* m_instanceDiagram;
    wxRadioButton* m_noInst;
    wxButton* m_oke;
    wxButton* m_cancel;

    a2dCameleonPtr m_cameleon;
////@end a2dCamCreate member variables
};

#endif
    // _CAMCREATE_H_
