// ---------------------------------------------------------------------------
// C:/Users/db348/art2d/trunk/wxArt2D/packages/wxart2d/apps/thumbo/src/thumbo_bind.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#include "a2dprec.h"

#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif

#include "wxlua/wxlstate.h"
#include "thumbowrap.h"

#ifdef __GNUC__
    #pragma GCC diagnostic ignored "-Wunused-variable"
#endif // __GNUC__

// ---------------------------------------------------------------------------
// wxLuaGetEventList_thumbo() is called to register events
// ---------------------------------------------------------------------------

wxLuaBindEvent* wxLuaGetEventList_thumbo(size_t &count)
{
    static wxLuaBindEvent eventList[] =
    {

        { 0, 0, 0 },
    };
    count = sizeof(eventList)/sizeof(wxLuaBindEvent) - 1;
    return eventList;
}

// ---------------------------------------------------------------------------
// wxLuaGetDefineList_thumbo() is called to register #define and enum
// ---------------------------------------------------------------------------

wxLuaBindNumber* wxLuaGetDefineList_thumbo(size_t &count)
{
    static wxLuaBindNumber numberList[] =
    {

        { 0, 0 },
    };
    count = sizeof(numberList)/sizeof(wxLuaBindNumber) - 1;
    return numberList;
}

// ---------------------------------------------------------------------------

// wxLuaGetStringList_thumbo() is called to register #define_string
// ---------------------------------------------------------------------------

wxLuaBindString* wxLuaGetStringList_thumbo(size_t &count)
{
    static wxLuaBindString stringList[] =
    {
        { "a2dTHUMBO_VERSION", a2dTHUMBO_VERSION, NULL },

        { 0, 0 },
    };
    count = sizeof(stringList)/sizeof(wxLuaBindString) - 1;
    return stringList;
}

// ---------------------------------------------------------------------------
// wxLuaGetObjectList_thumbo() is called to register object and pointer bindings
// ---------------------------------------------------------------------------

wxLuaBindObject* wxLuaGetObjectList_thumbo(size_t &count)
{
    static wxLuaBindObject objectList[] =
    {

        { 0, 0, 0, 0 },
    };
    count = sizeof(objectList)/sizeof(wxLuaBindObject) - 1;
    return objectList;
}

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_thumbo() is called to register global functions
// ---------------------------------------------------------------------------

// %function ThumboLuaProcCommandProcessor* a2dGetThumbo()
static int LUACALL wxLua_function_a2dGetThumbo(lua_State *L)
{
    // call a2dGetThumbo
    ThumboLuaProcCommandProcessor* returns = (ThumboLuaProcCommandProcessor*)a2dGetThumbo();
    // push the result datatype
    wxluaT_pushuserdatatype(L, returns, wxluatype_ThumboLuaProcCommandProcessor);

    return 1;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_a2dGetThumbo[1] = {{ wxLua_function_a2dGetThumbo, WXLUAMETHOD_CFUNCTION, 0, 0, g_wxluaargtypeArray_None }};

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_thumbo() is called to register global functions
// ---------------------------------------------------------------------------

wxLuaBindMethod* wxLuaGetFunctionList_thumbo(size_t &count)
{
    static wxLuaBindMethod functionList[] =
    {
        { "a2dGetThumbo", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_a2dGetThumbo, 1, NULL },

        { 0, 0, 0, 0 }, 
    };
    count = sizeof(functionList)/sizeof(wxLuaBindMethod) - 1;
    return functionList;
}



// ---------------------------------------------------------------------------
// wxLuaGetClassList_thumbo() is called to register classes
// ---------------------------------------------------------------------------

static const char* wxluaclassname_ThumboLuaProcCommandProcessor = "ThumboLuaProcCommandProcessor";
static const char* wxluaclassname_a2dLuaCentralCommandProcessor = "a2dLuaCentralCommandProcessor";

static const char* wxluabaseclassnames_ThumboLuaProcCommandProcessor[] = { wxluaclassname_a2dLuaCentralCommandProcessor, NULL };
static wxLuaBindClass* wxluabaseclassbinds_ThumboLuaProcCommandProcessor[] = { NULL };
// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------

extern wxLuaBindMethod ThumboLuaProcCommandProcessor_methods[];
extern int ThumboLuaProcCommandProcessor_methodCount;
extern void wxLua_ThumboLuaProcCommandProcessor_delete_function(void** p);




wxLuaBindClass* wxLuaGetClassList_thumbo(size_t &count)
{
    static wxLuaBindClass classList[] =
    {
        { wxluaclassname_ThumboLuaProcCommandProcessor, ThumboLuaProcCommandProcessor_methods, ThumboLuaProcCommandProcessor_methodCount, CLASSINFO(ThumboLuaProcCommandProcessor), &wxluatype_ThumboLuaProcCommandProcessor, wxluabaseclassnames_ThumboLuaProcCommandProcessor, wxluabaseclassbinds_ThumboLuaProcCommandProcessor, NULL, NULL, NULL, 0, &wxLua_ThumboLuaProcCommandProcessor_delete_function, }, 

        { 0, 0, 0, 0, 0, 0, 0 }, 
    };
    count = sizeof(classList)/sizeof(wxLuaBindClass) - 1;

    return classList;
}

// ---------------------------------------------------------------------------
// wxLuaBinding_thumbo() - the binding class
// ---------------------------------------------------------------------------

IMPLEMENT_DYNAMIC_CLASS(wxLuaBinding_thumbo, wxLuaBinding)

wxLuaBinding_thumbo::wxLuaBinding_thumbo() : wxLuaBinding()
{
    m_bindingName   = wxT("thumbo");
    m_nameSpace     = wxT("wx");
    m_classArray    = wxLuaGetClassList_thumbo(m_classCount);
    m_numberArray   = wxLuaGetDefineList_thumbo(m_numberCount);
    m_stringArray   = wxLuaGetStringList_thumbo(m_stringCount);
    m_eventArray    = wxLuaGetEventList_thumbo(m_eventCount);
    m_objectArray   = wxLuaGetObjectList_thumbo(m_objectCount);
    m_functionArray = wxLuaGetFunctionList_thumbo(m_functionCount);
    InitBinding();
}



// ---------------------------------------------------------------------------

wxLuaBinding* wxLuaBinding_thumbo_init()
{
    static wxLuaBinding_thumbo m_binding;

    if (wxLuaBinding::GetBindingArray().Index(&m_binding) == wxNOT_FOUND)
        wxLuaBinding::GetBindingArray().Add(&m_binding);

    return &m_binding;
}


