// ---------------------------------------------------------------------------
// teto.h - headers and wxLua types for wxLua binding
//
// This file was generated by genwxbind.lua 
// Any changes made to this file will be lost when the file is regenerated
// ---------------------------------------------------------------------------

#ifndef __HOOK_WXLUA_teto_H__
#define __HOOK_WXLUA_teto_H__

#include "wxbind/include/wxcore_bind.h"

#include "wxlua/wxlstate.h"
#include "wxlua/wxlbind.h"

// ---------------------------------------------------------------------------
// Check if the version of binding generator used to create this is older than
//   the current version of the bindings.
//   See 'bindings/genwxbind.lua' and 'modules/wxlua/wxldefs.h'
#if WXLUA_BINDING_VERSION > 30
#   error "The WXLUA_BINDING_VERSION in the bindings is too old, regenerate bindings."
#endif //WXLUA_BINDING_VERSION > 30
// ---------------------------------------------------------------------------

// binding class
class WXLUA_NO_DLLIMPEXP wxLuaBinding_teto : public wxLuaBinding
{
public:
    wxLuaBinding_teto();


private:
    DECLARE_DYNAMIC_CLASS(wxLuaBinding_teto)
};


// initialize wxLuaBinding_teto for all wxLuaStates
extern WXLUA_NO_DLLIMPEXP wxLuaBinding* wxLuaBinding_teto_init();

// ---------------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------------

#include "docv.h"
#include "wx/artbase/drawer2d.h"
#include "wx/docview/doccom.h"
#include "wx/editor/cancom.h"
#include "wx/editor/candocproc.h"

// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------

extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_TetoLuaProcCommandProcessor;



#endif // __HOOK_WXLUA_teto_H__

